# Generated by Django 5.2.3 on 2026-09-26 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('jurisdiction', models.CharField(choices=[('FEDERAL', 'Federal'), ('PROVINCIAL', 'Provincial'), ('MUNICIPAL', 'Municipal'), ('INSTITUTIONAL', 'Institutional'), ('COMMUNITY', 'Community')], default='FEDERAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('topic_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(help_text='When a human last confirmed this link was correct.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_sources', to='directory.organization')),
            ],
            options={
                'ordering': ['organization__name', 'title'],
            },
        ),
    ]
