# Generated by Django 5.2.3 on 2026-09-27 05:43

import django.db.models.deletion
import hashlib
import uuid
from django.db import migrations, models
from django.utils import timezone


def seed_verified_sections(apps, schema_editor):
    OfficialSource = apps.get_model("directory", "OfficialSource")
    OfficialSourceSection = apps.get_model("directory", "OfficialSourceSection")
    now = timezone.now()
    for source in OfficialSource.objects.all():
        text = source.description or source.title
        OfficialSourceSection.objects.get_or_create(
            source=source,
            position=1,
            defaults={
                "heading": source.title,
                "heading_path": source.title,
                "text": text,
                "content_hash": hashlib.sha256(text.encode()).hexdigest(),
                "active": True,
                "retrieved_at": now,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialsource',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='etag',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='final_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='last_modified',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='refresh_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='refresh_interval_hours',
            field=models.PositiveIntegerField(default=168),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='refresh_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('CHANGED', 'Changed - review required'), ('BROKEN', 'Broken')], default='VERIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='OfficialSourceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('final_url', models.URLField(max_length=500)),
                ('content_hash', models.CharField(max_length=64)),
                ('page_title', models.CharField(blank=True, max_length=300)),
                ('sections', models.JSONField(default=list)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='directory.officialsource')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSourceSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('heading_path', models.CharField(blank=True, max_length=700)),
                ('anchor', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(max_length=12000)),
                ('position', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('retrieved_at', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='directory.officialsource')),
            ],
            options={
                'ordering': ['source', 'position'],
                'constraints': [models.UniqueConstraint(fields=('source', 'position'), name='unique_source_section_position')],
            },
        ),
        migrations.RunPython(seed_verified_sections, migrations.RunPython.noop),
    ]
