# Generated by Django 5.2.3 on 2026-09-27 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialsource',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='title_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='url_fr',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='official_url_fr',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
