# Generated by Django 5.2.3 on 2026-09-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_officialsource_content_hash_officialsource_etag_and_more'),
        ('directory', '0002_officialsource_description_fr_and_more'),
    ]

    operations = [
    ]
