# Generated by Django 5.2.3 on 2026-09-26 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('goal', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING', 'Waiting'), ('ACTION_REQUIRED', 'Action required'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('current_state', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_code', models.CharField(choices=[('WAIT', 'Wait'), ('SUBMIT', 'Submit something'), ('UPLOAD', 'Upload a document'), ('CALL', 'Call the organization'), ('VISIT', 'Visit in person'), ('PROVIDE_DOCUMENT', 'Provide a document'), ('CONTACT_ORGANIZATION', 'Contact the organization'), ('NONE', 'Nothing recorded')], default='NONE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='directory.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INTERACTION', 'Interaction'), ('ACTION', 'Action'), ('STATUS_UPDATE', 'Status update'), ('DOCUMENT', 'Document'), ('NOTE', 'Note'), ('SOURCE', 'Source')], max_length=20)),
                ('channel', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('IN_PERSON', 'In person'), ('WEB', 'Web'), ('LETTER', 'Letter'), ('UPLOAD', 'Upload'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('raw_text', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('title', models.CharField(max_length=300)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('source_type', models.CharField(choices=[('OFFICIAL', 'Official'), ('USER_REPORTED', 'User reported'), ('COMMUNITY', 'Community'), ('AI_INTERPRETATION', 'AI interpretation')], default='USER_REPORTED', max_length=20)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breadcrumbs', to='directory.organization')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='journeys.journey')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['user', '-updated_at'], name='journeys_jo_user_id_24b79f_idx'),
        ),
        migrations.AddIndex(
            model_name='breadcrumb',
            index=models.Index(fields=['journey', 'occurred_at'], name='journeys_br_journey_906dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='breadcrumb',
            index=models.Index(fields=['journey', 'is_confirmed'], name='journeys_br_journey_ada8bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='breadcrumb',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id__isnull', False)), fields=('journey', 'request_id'), name='unique_journey_request_id'),
        ),
    ]
