# Generated by Django 5.2.3 on 2026-09-26 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_guides(apps, schema_editor):
    Journey = apps.get_model('journeys', 'Journey')
    Guide = apps.get_model('journeys', 'Guide')
    GuideStep = apps.get_model('journeys', 'GuideStep')
    summary = (
        "Use these suggested steps to organize the process. Verify current "
        "requirements with the responsible official service, then record what "
        "you actually do in your Journey."
    )
    generic = [
        ("Find the responsible official service", "Confirm which public organization owns this process before relying on forms or instructions."),
        ("Review the current official process", "Check the official source for current eligibility, required material, available channels, and instructions."),
        ("Prepare what the official service requests", "Create a checklist from the verified instructions and note what is already complete."),
        ("Complete the next official action", "Follow the verified process and review the information before submitting or attending."),
        ("Record confirmation and follow-up", "Add receipts, interactions, instructions, and outcomes without sensitive identifiers."),
    ]
    for journey in Journey.objects.all().iterator():
        guide, created = Guide.objects.get_or_create(
            journey=journey,
            defaults={"summary": summary, "generated_by": "rules"},
        )
        if created:
            GuideStep.objects.bulk_create([
                GuideStep(
                    guide=guide,
                    position=position,
                    title=title,
                    description=description,
                    organization_id=journey.primary_organization_id,
                )
                for position, (title, description) in enumerate(generic, start=1)
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('generated_by', models.CharField(default='rules', max_length=32)),
                ('needs_clarification', models.BooleanField(default=False)),
                ('clarification_question', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='journeys.journey')),
            ],
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=700)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_breadcrumb', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_guide_step', to='journeys.breadcrumb')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journeys.guide')),
                ('official_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_steps', to='directory.officialsource')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_steps', to='directory.organization')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='breadcrumb',
            name='guide_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breadcrumbs', to='journeys.guidestep'),
        ),
        migrations.AddConstraint(
            model_name='guidestep',
            constraint=models.UniqueConstraint(fields=('guide', 'position'), name='unique_guide_step_position'),
        ),
        migrations.RunPython(backfill_guides, migrations.RunPython.noop),
    ]
