# Generated by Django 5.2.3 on 2026-09-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_officialsource_content_hash_officialsource_etag_and_more'),
        ('journeys', '0002_guide_guidestep_breadcrumb_guide_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='citation_excerpt',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='citation_heading',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='citation_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='citation_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='official_source_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_steps', to='directory.officialsourcesection'),
        ),
    ]
