# Generated by Django 5.2.3 on 2026-09-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_guidestep_citation_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-updated_at', '-created_at', '-id']},
        ),
    ]
